language: node_js
node_js:
- 16.20.2
env:
  global:
  - MATTERMOST_CHANNEL=publication
  # MATTERMOST_HOOK_URL
  - secure: edtyHzxxjI8NuGF33bDUoMkkpmZeAGx+R1BYmmapqCfQ4eNMcbrBXe6kMXspmbBAM4ztbntEVJoH0fjQ7RVYqqK8jsVrQUtZ5ekZK1RUz5+1VJSl+3Sz6LLaT2FCC6/7oBDIvI+1OLWzyG9cxrFBbrurQo1sNHewHD8PWjgllF/QzHa0iupqzm/FjP5E1X1fM7QVFRnfyYWc1iqddjatJAavPX0HsvY0kDd152/PMFPCOK1pyF5VB4AvpE82f0ho0GNdURhdHu3zIcgAf+Nb+PEzNXxSFJxZhw0KzvzQAZKUK5om3eftzquhSg+aG6YFnovev7EFtBJ5ygoOyOIKPH6+BAEzC+d+NCfVolBiy1LBlqT8xQPETu4K+hC6p+OMHrroQFKYyiA5qth50HixaHMbhM/iDhQSlgKTdytumWvUBZ9JQ7JkbD052ZvPg+IcEh0OXrqBgIm0Q4j3ynKPYVIqcu2DuygZli9/SXJ7kJeyk1Q0yXKww91t3r9xBWYwW1l3A6IAWK7Vu7hrqyCXERTL6NGzD7xbZ1zCzGPhwR4Foc+wp/BUrOXPFAQRK417CGCJBAHAajlwf6NtcHEH9GAmylxAPU4vu9/9Zqh6I5C9UNzQokWmZevT2rOSU8hTdsVHzqRz96QemhEILwks3HPtuVTimiHOCE2VLX+df2w=
  # REGISTRY_TOKEN slug=bouyguestelecom editor=cozy space=default
  - secure: gJfx5f1y1avv4F+XRu7rEu4EE5GGbwzyp/UGtQRiIQ6f14v4d84tXbJ1TKTn3Z0khUnBQaSEbc9a0r+uWMlMp4oZ0II351dBWmzDhqQNrNocuvl2YGrlVtk2BNBrm+Ql9al4+Cl9oDUrtPEKgSfsKXhAJYtJmyL9D3ZIt4pRUcg+thOocpn/isEh9wtxbvjShB7CZcAcilTJsYKgAXGQSCqqlLHpnj5ShgTv88uiYphlLk3nCPRY/FOe0uHuYuHFa4PZ0HCNEm/sf0f5yhR276xenTbMSwlYqNkQqzj8/H30+NbXSmd1I4mnCN5AzbP0NGtNAwO4EkwqZ0n7bFCgaJ1NKzR14Ma7pPig7YdSRmlHr0j0j2sxxi/Qe9hzAHIBl/yn/TvXetU78VhPNpCQ9VTz8H5G+G8k2A4V5T2X6x53dTPDTDxqc9Q2pAi/zHnvo6r1OBmKGU+nBDWg9cz0cMDMbwSdVUnuLsPor7H2+wSo+7mIQ6BCBNGdqBQLNk+Pec9AZerZlucYAw45Ba3JqPL3HcJbT44Wc30rGYPHNRa8eb8HiRsUsT7fPfLC/B0DuOTUem3kIWRMHQjRsnhdN9SspfkynMK618NDTADaqq2llca0LJ//kJnE6nN9DDiEgMEoqhakKHzDWSPISiU0kdKAalVG2Xp9q3OFzqN16UM=
cache:
  yarn: true
  directories:
  - node_modules
branches:
  except:
  - build
  - build-debug
script:
- yarn lint
- yarn build
deploy:
- provider: script
  skip-cleanup: true
  script: DEPLOY_BRANCH=build yarn deploy && yarn cozyPublish
  on:
    branch:
    - master
    - main
- provider: script
  skip-cleanup: true
  script: DEPLOY_BRANCH=build yarn deploy && yarn cozyPublish --postpublish mattermost
  on:
    tags: true
before_install:
- openssl aes-256-cbc -K $encrypted_8ebb1ef83f64_key -iv $encrypted_8ebb1ef83f64_iv
  -in github_deploy_key.enc -out /tmp/github_deploy_key -d
- eval "$(ssh-agent -s)"
- if [[ -f /tmp/github_deploy_key ]]; then chmod 600 /tmp/github_deploy_key; fi
- if [[ -f /tmp/github_deploy_key ]]; then ssh-add /tmp/github_deploy_key; fi
after_deploy:
- rm -f /tmp/github_deploy_key
- ssh-add -D